### PR TITLE
Resampling & Aggregation parameters for get_series

### PR DESCRIPTION
**Pull request by jpo424**
Given the complexity of resampling and aggregation is handled by the api endpoint, this just formalizes the new group of parameters.

### CODE REVIEW

**Comment by KFoxder** [comment]
@jpo424 this looks good but do you want to add tests or more importantly documentation?

**Comment by jpo424** [comment]
all the documentation is on the site + reference guides. Existing tests cover response structure given these new params do not change the response structure. The kwargs for these parameter are part of the client method signature, so I'm not going to test that. The only logic to test is if those kwargs actually make it into the request url, and that seemed a pretty low value test. I had considered even doing that silly test, but given nothing happens to the response structure, the test didn't even provide a documentation advantage. Did you have a test in mind?

**Comment by jpo424** [comment]
I wont do this now, but we could add legit docs to this repo... we have a few client objects, each with a few methods, so it'll be helpful.

**Comment by KFoxder** [comment]
@jpo424 for the documentation I guess I meant more for the README examples which somehow I completely missed when looking at the changed files so disregard that. 

For the tests I was thinking just that, about actually making sure they get into the URL since that is their only purpose and making sure they get in there correctly

**Pull request merged**
